### ISSUE TITLE
Can't Compile from Command-Line or VSCode

### ISSUE THREAD

**Issue by aszepieniec** [starkware-libs/stone-prover#14]
I *can* compile using docker, but docker is rather a bit of a black box doesn't quite let me poke and prod in the way that I want to. I can't seem to get it compile from the command-line or from VSCode. I am running ubuntu.

I saw in the [presentation by Lior Goldberg and Gidi Kaempfer](https://www.youtube.com/watch?v=Rpz5iQTWbaA) that Lior walked through using VSCode. So I know that is possible. And presumably VSCode is invoking command line calls under the hood, so whatever it does should be reproducible on the command line.

Here's what goes wrong:

1. In VSCode, I get red squiggly lines under imports such as `#include "starkware/air/test_utils.h"`. The red squiggly line says:

 > #include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (/home/alan/repos/stone-prover/src/starkware/air/test_utils_test.cc).C/C++(1696)
 > cannot open source file "glog/logging.h" (dependency of "starkware/air/test_utils.h")C/C++(1696)

2. On the command line I run

```
$> cd build/
build/$> cmake ..
```

This command outputs a bunch of warnings or general information which I won't copy here (unless you say it might be relevant). In these warnings it says among other things that the linker had to search for these libraries: `dw, glog, gflags, pthread, gmock, gtest`. A bunch of other libraries including `/home/alan/repos/stone-prover/third_party/XKCP/KeccakP-1600-OptimizedAVX2/libKeccak1600F.a` have known full paths.

But after all the warnings or general info, the output contains this error:

```
CMake Error: Cannot determine link language for target "Keccak1600F".
CMake Error: CMake can not determine linker language for target: Keccak1600F
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Here's what I did so far:

 1. VSCode: install plugins C++ and CMake
 2. `sudo apt-get install googletest`
 3. `sudo apt-get install clang-12 clang++-12`
 4. Install [googletest](https://google.github.io/googletest/) by following the instructions on [this stack-exchange answer](https://stackoverflow.com/questions/72108314/how-do-i-build-and-use-googletest-gtest-and-googlemock-gmock-with-gcc-g-or/75719098#75719098), repeated below for convenience:
  - `git clone https://github.com/google/googletest.git`
  - `cd googletest`
  - `mkdir build`
  - `cd build`
  - `cmake ..`
  - `make`
  - `sudo make install`
5. Same sequence of instructions as (4) but for [gflags](https://github.com/gflags/gflags.git).

**Comment by LandauRaz** [comment]
Answered privately and mirroring here for visibility:
We could not recreate it locally, which is an indication you are missing dependencies needed to run this. You should consult the root Dockerfile to see what dependencies are installed ahead of complication.
