### ISSUE TITLE
Replace example from Cairo 0 with Cairo1

### ISSUE THREAD

**Issue by L0GYKAL** [starkware-libs/stone-prover#17]
As the current version of the language is Cairo 1 and Cairo 0 is getting deprecated.
This [section](https://github.com/starkware-libs/stone-prover?tab=readme-ov-file#creating-and-verifying-a-proof-of-a-cairozero-program): "Creating and verifying a proof of a CairoZero program" should be updated to Cairo in the case the manipulation isn't similar. Else, just change the title.

**Comment by LandauRaz** [comment]
Done, thanks for the input!
