### ISSUE TITLE
Does this support the current Cairo version?

### ISSUE THREAD

**Issue by jonZlotnik** [starkware-libs/stone-prover#3]
> [This repository contains a prover and a verifier for STARKs, and in particular for the CPU AIR underlying the CairoZero programming language.](https://github.com/starkware-libs/stone-prover/blob/3d5bb8bd991b7809a6d379c123c902667bac600f/README.md?plain=1#L8)

I'm a little confused with the CairoZero, Cairo 0, and Cairo (2.2?)

Is CairoZero somehow equivalent to [the current cairo release](https://github.com/starkware-libs/cairo) ?
Can we use this prover to generate proofs for programs written in Cairo 2.2?

The [feature parity doc](https://github.com/starkware-libs/cairo/blob/main/docs/FEATURE_PARITY.md) claims completeness.

@KineretS , this [Youtube video](https://youtu.be/01tIeGBHsek?si=uXf9FEKxqjarttsn) encourages us to start playing around, but all the nice documentation is about Cairo "greater than" 0

**Comment by maoudia-via** [comment]
Hello.

We are also very interested in using the stone-prover off-chain to prove Cairo(not 0) programs. 
Is there a plan to support this ?

**Comment by iliav-starkware** [comment]
Cairo0 is different from the current release and can already be proven by Stone.

For the current version, this functionality requires small modifications to the Cairo→CASM compiler and the VM. They are already in the works.
