### ISSUE TITLE
cpu_air_prover: command not found

### ISSUE THREAD

**Issue by HiteshMittal07** [starkware-libs/stone-prover#30]
on running the command used for generating proof after generating input files, the command for creating proof doesn't work and give command not found, why?

**Comment by LandauRaz** [comment]
Hey, can you please give more details on the steps to reproduce and the machinery you're using?

**Comment by HiteshMittal07** [comment]
It  is solved, actually the command provided in readme has to update little bit, it should have proper path of cpu air prover
