### ISSUE TITLE
Prover breaks when using arbitrary programs

### ISSUE THREAD

**Issue by entropidelic** [starkware-libs/stone-prover#5]
Hello, I have been working on proving Cairo programs, starting with the example that's showcased in the readme. 

We tried to change the test program, and the prover fails. 

The same happens with the readme example program when the input in the `fibonacci_input.json` file is changed. For example, when changing the input from 10 to 10000, the prover errors with the following:
```
terminate called after throwing an instance of ‘starkware::StarkwareException’
  what():  /app/src/starkware/stark/stark.cc:187: Fri parameters do not match stark degree bound. Expected FRI degree from FriParameters: 32768. STARK: 1048576
```
This seems related to issue #4, but it not clear how this should be solved.

Does the configuration in `cpu_air_params.json` depend on the program we want to prove and its inputs? If so, how should it be adjusted to properly generate a proof?

**Comment by gkaempfer** [comment]
Indeed it's related to issue #4. If you change the Fibonacci example, the trace may grow (in your case it grew from 2^15 in the example to 2^20). Hence, you need to set the FRI steps accordingly to add up to 20 (instead of 15 for 2^15 trace length).
