### ISSUE TITLE
cpu_air_prover has a hidden assumption about trace and memory

### ISSUE THREAD

**Issue by maoudia-via** [starkware-libs/stone-prover#9]
One of the inputs of cpu_air_prover is private_input_file.
The file contains references to the trace and memory file.
It would be nice to have those as input parameters to the program so they can be clearly documented.

**Comment by gkaempfer** [comment]
The Stone pover is a generic STARK prover to which there is a set of standard inputs including the private_input. Depending on the Statement, the format of the private_input may change but we chose not to have different input parameters for each Stone Statement.
